apiVersion: apps/v1
kind: Deployment
metadata:
  name: glpi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glpi
  template:
    metadata:
      labels:
        app: glpi
    spec:
      containers:
        - name: glpi
          image: diouxx/glpi  # OR use your custom image
          ports:
            - containerPort: 80
          volumeMounts:
            - name: glpi-storage
              mountPath: /var/www/html/glpi
      volumes:
        - name: glpi-storage
          persistentVolumeClaim:
            claimName: glpi-pvc

