name: CI/CD Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:   # allows manual trigger too

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region eu-north-1 --name GLPI-Cluster

      - name: Authenticate with EKS
        run: aws eks get-token --cluster-name GLPI-Cluster --region eu-north-1 > /dev/null

      - name: Check kubectl context
        run: kubectl config current-context

      - name: Deploy to Kubernetes
        run: |
          kubectl apply --validate=false -f k8s/
          kubectl rollout status deployment/glpi

